name: API On GitHub Actions
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "10 2 * * *"     # Runs every day at 2:10 AM UTC
jobs:
  API:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v4
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Installing all necessary packages
        run: pip install -r requirements.txt
      - name: Running Python
        env:
          OPENAI_ADMIN_API_KEY: ${{ secrets.OPENAI_ADMIN_API_KEY }}
        run: |
          python GetOpenAIQuota.py

      - name: Commit and Push The Results From Python Action
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git add -A
         git add *.json 
         git commit -m "⬆️ GitHub Actions Results added" || true
         git push || true
